USE [master]
GO

/****** Object:  Database [MiBilletera]    Script Date: 29/11/2022 12:16:15 ******/
CREATE DATABASE [MiBilletera]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MiBilletera', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MiBilletera.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MiBilletera_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MiBilletera_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MiBilletera].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MiBilletera] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MiBilletera] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MiBilletera] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MiBilletera] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MiBilletera] SET ARITHABORT OFF 
GO

ALTER DATABASE [MiBilletera] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MiBilletera] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MiBilletera] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MiBilletera] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MiBilletera] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MiBilletera] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MiBilletera] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MiBilletera] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MiBilletera] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MiBilletera] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MiBilletera] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MiBilletera] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MiBilletera] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MiBilletera] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MiBilletera] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MiBilletera] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MiBilletera] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MiBilletera] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MiBilletera] SET  MULTI_USER 
GO

ALTER DATABASE [MiBilletera] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MiBilletera] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MiBilletera] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MiBilletera] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MiBilletera] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MiBilletera] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [MiBilletera] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MiBilletera] SET  READ_WRITE 
GO


